# Generated by Django 3.2.20 on 2023-07-31 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_auto_20230712_0527'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_user_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('target', models.CharField(max_length=100)),
                ('period', models.CharField(max_length=100)),
            ],
        ),
    ]
